spring:

  datasource:
    url: jdbc:mysql://localhost:33061/weather_prod
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # this tell Hibernate to automatically validate whether the models match the db schema
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect