spring:
  profiles: prod

datasource:
  url: jdbc:mysql://localhost:33061/weather_prod
  username: ${username}
  password: ${password}
  driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # this tell Hibernate to automatically update the db schema to match object models
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect